CREATE DATABASE ECOMMERCE_ANALYTICS;
USE ECOMMERCE_ANALYTICS;
SELECT * FROM Customers_review_table;
SELECT * FROM Customers_table;
SELECT * FROM Order_items_table;
SELECT * FROM Orders_table;
SELECT * FROM Payments_table;
SELECT * FROM Products_table;
SELECT * FROM Sellers_table;


---#1 ALTER THE COLUMN DATA TYPES---

ALTER TABLE Customers_review_table
ALTER COLUMN review_answer_timestamp DATETIME;
ALTER TABLE Customers_review_table
ALTER COLUMN review_score INT;
ALTER TABLE customers_table
ALTER COLUMN customer_zip_code_prefix INT;
ALTER TABLE Order_items_table
ALTER COLUMN freight_value FLOAT;
ALTER TABLE Order_items_table
ALTER COLUMN order_item_id INT;
ALTER TABLE Orders_table
ALTER COLUMN order_estimated_delivery_date DATETIME;

ALTER TABLE payments_table
ALTER COLUMN payment_installments INT;
ALTER TABLE payments_table
ALTER COLUMN payment_sequential INT;
ALTER TABLE Products_table
ALTER COLUMN product_name_lenght INT
ALTER TABLE Products_table
ALTER COLUMN product_description_lenght INT;
ALTER TABLE Products_table
ALTER COLUMN product_photos_qty INT;
ALTER TABLE Products_table
ALTER COLUMN product_weight_g INT;
ALTER TABLE Products_table
ALTER COLUMN product_length_cm INT;
ALTER TABLE Products_table
ALTER COLUMN product_height_cm INT;
ALTER TABLE Products_table
ALTER COLUMN product_width_cm INT;
ALTER TABLE Sellers_table
ALTER COLUMN seller_zip_code_prefix INT; 


----#1. What is the cumulative revenue generated by the platform, and what trends can be observed in its evolution over time?	
---CUMULATIVE REVENUE AND TREND OVER TIME---

SELECT 
	YEAR( O.order_purchase_timestamp) AS 'ORDER_YEAR',
	MONTH( O.order_purchase_timestamp) AS 'ORDER_MONTH',
	SUM (P.payment_value) AS 'REVENUE_THIS_PERIOD',
	SUM(SUM (P.payment_value)) OVER (ORDER BY YEAR( O.order_purchase_timestamp), MONTH( O.order_purchase_timestamp)) AS 'CUMULATIVE_REVENUE'
FROM Orders_table O
JOIN Payments_table P
ON O.order_id = P.order_id
GROUP BY YEAR( O.order_purchase_timestamp), MONTH( O.order_purchase_timestamp)
ORDER BY ORDER_YEAR , ORDER_MONTH;


----# WE CAN SEE INCREASE IN REVENUE IS BEING GENERATED OVER THE TIME---

----#2. Which product categories are the most favored on the platform, and how do their sales figures compare with each other?
----MOST FAVOURED CATEGORIES AND SALE COMPARISON----


SELECT
	P.product_category_name,
	COUNT(OI.order_item_id) AS 'TOTAL_ITEMS_SOLD',
	COUNT(DISTINCT(OI.order_id)) AS 'TOTAL_ORDERS',
	SUM(OI.price) AS 'TOTAL_SALES_REVENUE'
FROM Order_items_table OI
JOIN Products_table P
ON OI.product_id = P.product_id
GROUP BY P.product_category_name
ORDER BY TOTAL_SALES_REVENUE DESC;

---# WE CAN SEE WHICH PRODUCT CATEGORY GENERATES MOST AND LEAST REVENUE SALES----


----#3. What is the mean order value (AOV) on the platform, and how does it differ across various product categories or payment methods?
---. Mean Order Value (AOV) Across Categories and Payment Methods


---MEAN/AOV---
SELECT 
	AVG(payment_value) AS 'MEAN_ORDER_VALUE'
FROM Payments_table;

---AOV BY PRODUCT CATEGORY---

SELECT 
	P.product_category_name,
	AVG(OI.price) AS 'MEAN_ORDER_VALUE'
FROM Order_items_table OI
JOIN Products_table P
ON OI.product_id = P.product_id
GROUP BY P.product_category_name
ORDER BY MEAN_ORDER_VALUE DESC;

---AOV BY PAYMENT TYPE---

SELECT 
	payment_type,
	AVG(payment_value) AS 'MEAN_ORDER_VALUE'
FROM Payments_table
GROUP BY payment_type
ORDER BY MEAN_ORDER_VALUE DESC;

----#4. How many active sellers operate on the platform, and how does this count fluctuate over time?
----. Active Sellers and Their Growth Trends

SELECT
	YEAR(O.order_purchase_timestamp)AS 'ORDER_YEAR',
	MONTH(O.order_purchase_timestamp)AS 'ORDER_MONTH',
	COUNT(DISTINCT(OI.seller_id)) AS 'ACTIVE_SELLERS'
FROM Orders_table O 
JOIN Order_items_table OI 
ON OI.order_id = O.order_id
GROUP BY YEAR(O.order_purchase_timestamp) ,MONTH(O.order_purchase_timestamp) 
ORDER BY ORDER_MONTH , ORDER_YEAR;


---#5. What is the breakdown of seller ratings on the platform, and how does this influence sales performance?
---. Seller Ratings and Impact on Sales Performance

----calculating seller's avg review score----
SELECT 
	OI.seller_id , 
	AVG(CR.review_score) AS 'AVG_REVIEW_SCORE',
	COUNT(CR.review_score) AS 'NUM_REVIEWS'
FROM Order_items_table OI
JOIN Customers_review_table CR
ON OI.order_id = CR.order_id
GROUP BY OI.seller_id;

----calculating seller's total sales
SELECT
	seller_id , 
	SUM(price) AS 'TOTAL_SALES',
	COUNT(order_item_id) AS 'TOTAL_ITEMS_SOLD'
FROM Order_items_table
GROUP  BY seller_id;

---combining two queries to get review score and dales performance---

SELECT 
	OI.seller_id , 
	AVG(CR.review_score) AS 'AVG_REVIEW_SCORE',
	COUNT(CR.review_score) AS 'NUM_REVIEWS',
	SUM(OI.price) AS 'TOTAL_SALES',
	COUNT(OI.order_item_id) AS 'TOTAL_ITEMS_SOLD'
FROM Order_items_table OI
JOIN Customers_review_table CR
ON OI.order_id = CR.order_id
GROUP BY OI.seller_id
ORDER BY AVG_REVIEW_SCORE DESC , TOTAL_SALES DESC;


----#6. How many customers have made repeat purchases on the platform, and what proportion of total sales do they represent?
--- Repeat Customer Analysis and Sales Contribution---

---IDENTIFY REPEATED CUSTOMERS--
SELECT customer_id
FROM Orders_table
GROUP BY customer_id
HAVING COUNT(order_id) > 1;

----COUNT OF REPEAT CUSTOMERS AND TOTAL CUSTOMERS---
SELECT
	COUNT(DISTINCT customer_id) AS 'REPEAT_CUSTOMER_COUNT'
FROM Orders_table
GROUP BY customer_id
HAVING COUNT(order_id) > 1;

SELECT 
COUNT(DISTINCT customer_id) AS 'TOTAL_CUSTOMER_COUNT'
FROM Orders_table;

---PROPORTION OF ORDERS AND REVENUE BY REPEAT CUSTOMERS---
WITH REPEAT_CUSTOMERS AS(
	SELECT customer_id
	FROM Orders_table
	GROUP BY customer_id
	HAVING COUNT(order_id) > 1
)
SELECT 
	COUNT(DISTINCT O.order_id) AS 'REPEAT_CUSTOMER_ID',
	SUM(OI.PRICE) AS 'REPEAT_CUSTOMER_REVENUE'
FROM Orders_table O
JOIN REPEAT_CUSTOMERS RC ON O.customer_id = RC.customer_id
JOIN Order_items_table OI ON O.order_id = OI.order_id

SELECT 
	COUNT(DISTINCT O.order_id) AS 'TOTAL_ORDERS',
	SUM(OI.price) AS 'TOTAL_REVENUE'
FROM Orders_table O
JOIN Order_items_table OI 
ON O.order_id = OI.order_id;


---#7. What is the mean(Avg) customer rating for products available on the platform, and what influence does this have on sales performance?
----Mean Customer Ratings and Impact on Sales--

SELECT P.product_id , P.product_category_name,
	AVG(CR.review_score) AS 'AVG_REVIEW_SCORE',
	COUNT(CR.review_score) AS 'NUM_REVIEWS',
	SUM(OI.price) AS 'TOTAL_SALES',
	COUNT(OI.order_item_id) AS 'ITEMS_SOLD'
FROM Products_table P
JOIN Order_items_table OI ON P.product_id = OI.order_id
JOIN Customers_review_table CR ON OI.order_id = CR.order_id
GROUP BY P.product_id, P.product_category_name
ORDER BY AVG_REVIEW_SCORE DESC , TOTAL_SALES DESC;

---#8. What is the average rate of order cancellations on the platform, and how does this impact the performance of sellers?
----Top-Selling Products and Sales Evolution

----SELLER WISE CANCELLATION RATE----
WITH SELLER_ORDERS AS(
	SELECT
		OI.seller_id,
		O.order_id,
		O.order_status
	FROM Order_items_table OI
	JOIN Orders_table O ON OI.order_id = O.order_id
	GROUP BY OI.seller_id, O.order_id , O.order_status
)
SELECT 
	seller_id , 
	COUNT(CASE WHEN order_status = 'cancelled' THEN 1 END) AS 'CANCELLED_ORDERS',
	COUNT(order_id) AS 'TOTAL_ORDERS',
	CAST(COUNT(CASE WHEN order_status = 'cancelled' THEN 1 END) AS FLOAT) / COUNT(order_id) AS 'CANCELLATION_RATE'
FROM SELLER_ORDERS
GROUP BY seller_id
ORDER BY CANCELLATION_RATE DESC;

---#9. What are the top 3-selling products on the platform, and how have their sales trends evolved over time?
----Impact of Customer Reviews on Sales and Product Performance

---FIND TOP 3 SELLING PRODUCTS (BY SALES)
SELECT TOP 3 
	OI.product_id , 
	SUM(OI.price) AS 'TOTAL_SALES',
	COUNT(OI.order_item_id) AS 'TOTAL_ITEMS_SOLD'
FROM Order_items_table OI
GROUP BY OI.product_id
ORDER BY TOTAL_SALES DESC;

---MONTHLY TREND FRO TOP 3 SELLING PRODUCTS---
SELECT
	OI.product_id , 
	MONTH(O.order_purchase_timestamp) AS 'ORDER_MONTH',
	YEAR(O.order_purchase_timestamp) AS 'ORDER_YEAR',
	SUM(OI.price)AS 'MONTHLY_SALES',
	COUNT(OI.order_item_id) AS 'ITEMS_SOLD'
FROM Order_items_table OI
JOIN orders_table O 
ON OI.order_id = O.order_id
WHERE OI.product_id IN ('bb50f2e236e5eea0100680137654686c' , '6cdd53843498f92890544667809f1595 ' , ' d6160fb7873f184099d9bc95e30376af' )
GROUP BY OI.product_id , YEAR(O.order_purchase_timestamp), MONTH(O.order_purchase_timestamp)
ORDER BY OI.product_id , ORDER_YEAR , ORDER_MONTH;






