BULK INSERT [HSP DATASET]
FROM 'C:\Users\pc\Desktop\ocd_patient_dataset.csv'
WITH (
     FIRSTROW = 2,
	 FIELDTERMINATOR = ',',
	 ROWTERMINATOR = '\n',
	 TABLOCK
);

USE Healthcare_Sample_Project;
       
SELECT * FROM [HSP DATASET];

---1. COUNT AND % OF F VS M THT HAVE OCD AND AVG OBSESSION SCORE BY GENDER

SELECT
GENDER,
COUNT ([PATIENT ID]) AS PATIENT_COUNT,
ROUND(AVG(CAST ([Y-BOCS Score (Obsessions)] AS float)),2) AS AVG_OBS_SCORE
FROM [HSP DATASET]
GROUP BY Gender
ORDER BY PATIENT_COUNT;

SELECT
GENDER,
COUNT ([PATIENT ID]) AS PATIENT_COUNT,
ROUND(AVG(CAST ([Y-BOCS Score (Obsessions)] AS float)),2) AS AVG_OBS_SCORE
INTO #GENDERDATA1
FROM [HSP DATASET]
GROUP BY Gender
ORDER BY PATIENT_COUNT;

SELECT 
  SUM (CASE WHEN GENDER = 'FEMALE' THEN PATIENT_COUNT ELSE 0 END) AS COUNT_FEMALE,
  SUM (CASE WHEN GENDER = 'MALE' THEN PATIENT_COUNT ELSE 0 END) AS COUNT_MALE
 
 FROM #GENDERDATA1; 

 SELECT
 ROUND(SUM (CASE WHEN GENDER = 'FEMALE' THEN PATIENT_COUNT ELSE 0 END)/
  (SUM (CASE WHEN GENDER = 'MALE' THEN PATIENT_COUNT ELSE 0 END)+SUM (CASE WHEN GENDER = 'FEMALE' THEN PATIENT_COUNT ELSE 0 END))*100,2) 
  AS PCT_FEMALE,

   ROUND(SUM (CASE WHEN GENDER = 'MALE' THEN PATIENT_COUNT ELSE 0 END)/
  (SUM (CASE WHEN GENDER = 'FEMALE' THEN PATIENT_COUNT ELSE 0 END)+SUM (CASE WHEN GENDER = 'MALE' THEN PATIENT_COUNT ELSE 0 END))*100,2) 
  AS PCT_FEMALE

  FROM #GENDERDATA1;


---2. COUNT OF PATIENTS BY ETHNICITY AND THEIR RESPECTIVE AVG OBSESSION SCORE.

SELECT 
Ethnicity , 
COUNT([Patient ID]) AS PATIENT_COUNT,
ROUND(AVG(CAST ([Y-BOCS Score (Obsessions)] AS float)),2) AS OBS_SCORE

FROM [HSP DATASET]
GROUP BY Ethnicity
ORDER BY PATIENT_COUNT;

SELECT 
Ethnicity , 
COUNT([Patient ID]) AS PATIENT_COUNT,
ROUND(AVG(CAST ([Y-BOCS Score (Obsessions)] AS float)),2) AS OBS_SCORE
INTO #ETHNICITY
FROM [HSP DATASET]
GROUP BY Ethnicity
ORDER BY PATIENT_COUNT;
SELECT * FROM #ETHNICITY;


----3. NO. OF PEOPLE DIAGNOSED WITH OCD MoM

SELECT 




----4.WHAT IS THE MOST COMMON OBSESSION TYPE (COUNT) AND ITS RESPECTIVE AVG OBS SCORE.

SELECT 
([Obsession Type]) ,
COUNT ([PATIENT ID]) AS PATIENT_COUNT,
AVG(CAST ([Y-BOCS Score (Obsessions)] AS float)) AS OBS_SCORE
FROM [HSP DATASET];


---5. WHAT IS THE MOST COMMON COMPULSION TYPE (COUNT) AND ITS RESPECTIVE AVG OBS SCORE.

 

 




